language: android

jdk:
  - openjdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
  - sdkmanager tools

script: ./gradlew check --stacktrace

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
